In [2]:
import numpy as np

In [3]:
a = np.array([[1,2],[3,4]])
np.sum(a,0)

array([4, 6])

In [5]:
a = np.array([[-1,2],[3,4]])

In [6]:
np.maximum(a, 0)

array([[0, 2],
       [3, 4]])

In [10]:
b = (a>0) * 2
print(b)

[[0 2]
 [2 2]]
