In [1]:
import numpy as np

In [3]:
a = np.array([[1,2],[3,4]])
np.sum(a,0)

array([4, 6])

In [5]:
a = np.array([[-1,2],[3,4]])

In [6]:
np.maximum(a, 0)

array([[0, 2],
       [3, 4]])

In [10]:
b = (a>0) * 2
print(b)

[[0 2]
 [2 2]]


In [16]:
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[1,1]])
print(a+b)
print(a.shape)
print(b.shape)

[[2 3]
 [4 5]
 [6 7]]
(3, 2)
(1, 2)
